dubbo:
  application:
    name: dubbo-provider
  registry:
    address: 10.27.100.113:2181
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.27.100.171:3306/gmall_study?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8082

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl